# These are supported funding model platforms

# GitHub Sponsors
# github: [pilotstack-app]

# Open Collective
# open_collective: pilotstack

# Ko-fi
# ko_fi: pilotstack

# Patreon
# patreon: pilotstack

# Custom sponsorship links
custom: ['https://pilotstack.app/#pricing', 'https://pilotstack.app/#contact']
